import Head from "next/head";
import { Fragment } from "react";

type Props = {};

const Home = (props: Props) => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome!</h1>
      </main>
    </Fragment>
  );
};

export default Home;
